### ISSUE TITLE
Filter by open files?

### ISSUE THREAD

**Issue by NTShop** [monsterkodi/tree-view-filter#10]
Is it possible to filter the treeview to only show open files? If not would you consider adding that as a feature?

**Comment by monsterkodi** [comment]
Hello NTShop,
yes, that would be possible. 
But no, I am not interested in adding any new feature to the plugin.
Sorry :)

**Comment by NTShop** [comment]
No worries, we can fork it and add that. Thanks for considering.

**Comment by monsterkodi** [comment]
No problem. 

There is a plugin out there that shows the opened files above the tree view:

https://atom.io/packages/opened-files
https://atom.io/packages/open-files

Maybe one of them does what you need.
