### ISSUE TITLE
Active by default

### ISSUE THREAD

**Issue by mjharris2407** [monsterkodi/tree-view-filter#11]
I keep having toggle the tree view filter on when I start atom. There should be an option to have this always active. It's on of my favorite tools for the managing files and projects now.

**Comment by monsterkodi** [comment]
Hi Matt, 
yes, that might be useful. 
I will see what I can do.

**Comment by monsterkodi** [comment]
I just checked it and on my machine it remembers the activation state: 
If it was activated when Atom got closed, it will be activated automatically next time Atom starts.
It does not remember and set the filter text though. 
Can you please let me know what exactly you would change/expect?
