### ISSUE TITLE
the font of filter pattern editor is very small

### ISSUE THREAD

**Issue by X-G** [monsterkodi/tree-view-filter#3]
![qq 20150614144556](https://cloud.githubusercontent.com/assets/6829403/8148581/1573dacc-12a4-11e5-8f5b-7b28592d2317.png)

When I use [Ond Dark UI](https://atom.io/packages/one-dark-ui) which can change the UI font size.
The filter editor looks very small as the screenshot shows.
I think it will be better if the filter font size follows the UI theme font size.

**Comment by monsterkodi** [comment]
hello X-G,
that looks not very nice.
I will try to fix it soon,
thanks for reporting this,
yours monsterkodi

**Comment by monsterkodi** [comment]
It should behave better now, let me know if it still looks crappy.

**Comment by X-G** [comment]
It looks great now.
Thanks monsterkodi.
