### ISSUE TITLE
Filter doesn't run when expanding a directory in the tree view.

### ISSUE THREAD

**Issue by waltdestler** [monsterkodi/tree-view-filter#8]
Typing in a filter or setting a global filter and then expanding (clicking on its little arrow) a folder in the tree view doesn't filter out non-matching files in the newly-opened folder.

**Comment by monsterkodi** [comment]
Hello Walt,
this is a known issue and can't be fixed without changes to the tree-view itself. 
I made a PR for this to work (https://github.com/atom/tree-view/pull/414) almost 2 years ago.
Unfortunately that got never approved. 
I am sorry, but I don't think this will ever be solved.

**Comment by monsterkodi** [comment]
hi walt,
i found a way to make this happen without the pending changes to the tree-view.
if you are still interested, you could try out the latest version (0.4.6).
